name: GH page

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: build
      env:
        GENERATE_SOURCEMAP: false
      run: yarn && yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        build_dir: build
